import type { PlaceDef } from "../core/types";

/**
 * Every place on the globe. `load` is the only thing that makes a place
 * enterable; its scene module is code-split so the globe starts fast.
 */
export const PLACES: PlaceDef[] = [
  {
    id: "tokyo-konbini",
    name: "Rainy Night Konbini",
    native: "雨夜のコンビニ",
    locality: "Tokyo",
    localityNative: "東京",
    country: "Japan",
    lat: 35.7101,
    lon: 139.8107,
    timeZone: "Asia/Tokyo",
    status: "live",
    weather: "Rain · 14°C",
    accent: "#4fe3c1",
    load: () => import("./tokyo-konbini/index"),
  },
  {
    // Stair head 35.68502, 139.72330 (29.4 m); looking down the flight faces a bearing of ~33°.
    id: "suga-shrine-stairs",
    name: "Suga Shrine Stairs",
    native: "須賀神社の男坂",
    locality: "Yotsuya, Tokyo",
    localityNative: "四谷",
    country: "Japan",
    lat: 35.68502,
    lon: 139.7233,
    timeZone: "Asia/Tokyo",
    status: "live",
    weather: "Clear · 31°C",
    accent: "#ff5a4e",
    load: () => import("./suga-shrine-stairs/index"),
  },
  {
    id: "sangubashi-crossing",
    name: "Sangubashi in Bloom",
    native: "桜の参宮橋３号踏切",
    locality: "Yoyogi, Tokyo",
    localityNative: "代々木",
    country: "Japan",
    lat: 35.67528,
    lon: 139.69175,
    timeZone: "Asia/Tokyo",
    status: "live",
    weather: "Spring breeze · 17°C",
    accent: "#f0a7c3",
    load: () => import("./sangubashi-crossing/index"),
  },
  {
    id: "hong-kong-dai-pai-dong",
    name: "Dai Pai Dong under Neon",
    native: "霓虹大排檔",
    locality: "Hong Kong",
    localityNative: "香港",
    country: "China",
    lat: 22.3193,
    lon: 114.1694,
    timeZone: "Asia/Hong_Kong",
    status: "soon",
    weather: "Humid · 27°C",
    accent: "#ff4f7a",
  },
  {
    id: "seoul-pojangmacha",
    name: "Pojangmacha in the Snow",
    native: "눈 오는 포장마차",
    locality: "Seoul",
    localityNative: "서울",
    country: "South Korea",
    lat: 37.5665,
    lon: 126.978,
    timeZone: "Asia/Seoul",
    status: "soon",
    weather: "Snow · −3°C",
    accent: "#ff8a3d",
  },
  {
    id: "shanghai-longtang",
    name: "Longtang after Midnight",
    native: "午夜弄堂",
    locality: "Shanghai",
    localityNative: "上海",
    country: "China",
    lat: 31.2304,
    lon: 121.4737,
    timeZone: "Asia/Shanghai",
    status: "soon",
    weather: "Mist · 18°C",
    accent: "#ffcf5a",
  },
  {
    id: "mumbai-chai-stall",
    name: "Monsoon Chai Stall",
    native: "मानसून चाय",
    locality: "Mumbai",
    localityNative: "मुंबई",
    country: "India",
    lat: 19.076,
    lon: 72.8777,
    timeZone: "Asia/Kolkata",
    status: "soon",
    weather: "Monsoon · 28°C",
    accent: "#ffb347",
  },
  {
    id: "istanbul-last-ferry",
    name: "Last Ferry at Blue Hour",
    native: "Mavi Saatte Son Vapur",
    locality: "Istanbul",
    localityNative: "İstanbul",
    country: "Türkiye",
    lat: 41.0082,
    lon: 28.9784,
    timeZone: "Europe/Istanbul",
    status: "soon",
    weather: "Breeze · 16°C",
    accent: "#6ab8ff",
  },
  {
    id: "paris-cafe",
    name: "Café at Closing Time",
    native: "Le café à la fermeture",
    locality: "Paris",
    localityNative: "Paris",
    country: "France",
    lat: 48.8566,
    lon: 2.3522,
    timeZone: "Europe/Paris",
    status: "soon",
    weather: "Drizzle · 11°C",
    accent: "#ffd28a",
  },
  {
    id: "london-pub",
    name: "Pub in the Drizzle",
    native: "Pub in the Drizzle",
    locality: "London",
    localityNative: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lon: -0.1278,
    timeZone: "Europe/London",
    status: "soon",
    weather: "Drizzle · 9°C",
    accent: "#e8c07a",
  },
  {
    id: "reykjavik-harbour",
    name: "Aurora over the Harbour",
    native: "Norðurljós við höfnina",
    locality: "Reykjavík",
    localityNative: "Reykjavík",
    country: "Iceland",
    lat: 64.1466,
    lon: -21.9426,
    timeZone: "Atlantic/Reykjavik",
    status: "soon",
    weather: "Clear · −6°C",
    accent: "#7dffb2",
  },
  {
    id: "new-york-diner",
    name: "Diner at 3 AM",
    native: "Diner at 3 AM",
    locality: "New York",
    localityNative: "New York",
    country: "United States",
    lat: 40.7128,
    lon: -74.006,
    timeZone: "America/New_York",
    status: "soon",
    weather: "Steam · 7°C",
    accent: "#ff5f5f",
  },
  {
    id: "san-francisco-russian-hill",
    name: "Fog over Russian Hill",
    native: "Fog over Russian Hill",
    locality: "San Francisco",
    localityNative: "San Francisco",
    country: "United States",
    lat: 37.7749,
    lon: -122.4194,
    timeZone: "America/Los_Angeles",
    status: "soon",
    weather: "Fog · 12°C",
    accent: "#ff9e6b",
  },
  {
    id: "mexico-city-taqueria",
    name: "Taquería at Midnight",
    native: "Taquería a medianoche",
    locality: "Mexico City",
    localityNative: "Ciudad de México",
    country: "Mexico",
    lat: 19.4326,
    lon: -99.1332,
    timeZone: "America/Mexico_City",
    status: "soon",
    weather: "Clear · 15°C",
    accent: "#ff4fd8",
  },
  {
    id: "rio-hillside",
    name: "Hillside Lights",
    native: "Luzes do Morro",
    locality: "Rio de Janeiro",
    localityNative: "Rio de Janeiro",
    country: "Brazil",
    lat: -22.9068,
    lon: -43.1729,
    timeZone: "America/Sao_Paulo",
    status: "soon",
    weather: "Warm · 24°C",
    accent: "#5fff9e",
  },
  {
    id: "sydney-harbour",
    name: "Harbour Storm",
    native: "Harbour Storm",
    locality: "Sydney",
    localityNative: "Sydney",
    country: "Australia",
    lat: -33.8688,
    lon: 151.2093,
    timeZone: "Australia/Sydney",
    status: "soon",
    weather: "Storm · 19°C",
    accent: "#63d2ff",
  },
  {
    id: "cairo-rooftop",
    name: "Rooftop over the Nile",
    native: "سطح فوق النيل",
    locality: "Cairo",
    localityNative: "القاهرة",
    country: "Egypt",
    lat: 30.0444,
    lon: 31.2357,
    timeZone: "Africa/Cairo",
    status: "soon",
    weather: "Dry · 22°C",
    accent: "#ffc36b",
  },
];

export function placeById(id: string): PlaceDef | undefined {
  return PLACES.find((p) => p.id === id);
}

export function localTime(place: PlaceDef, date = new Date()): string {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: place.timeZone,
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date);
}
