import cityUrl from "../../data/lights-city.bin?url";
import signalsUrl from "../../data/lights-signals.bin?url";
import trafficUrl from "../../data/lights-traffic.bin?url";
import { LightSet, type Light } from "../../../shared/lights";

/**
 * The city-lights field, generated by the research script
 * `scripts/vista-lights.ts` from OpenFreeMap vector tiles (OpenMapTiles
 * schema, z14 within 8 km and along Wilshire, z13 over the basin), the
 * packed DEM and the viewshed of the terraces:
 *
 * - `lights-city.bin`: streetlights by road class and spacing with the
 *   September 2015 LED / sodium mix by city, lit windows, fuel-station
 *   canopies and lit fields; individual within 1 km of the terraces (windows
 *   600 m), merged beyond into one light per angular cell seen from the
 *   terraces (~0.35°, energy kept), sized so the Terrace view holds ≤ 19k;
 * - `lights-signals.bin`: traffic signals at major crossings within 6.5 km,
 *   red / amber / green heads cycling twice per loop;
 * - `lights-traffic.bin`: freeway and boulevard streams (path lights),
 *   headlights toward the terraces, tail lights away.
 *
 * Records are columns (see the script): "PLIT", count, flags, f32 x y z,
 * u8 colour, f32 intensity and radius, u8 phase and twinkle, then the
 * optional path and blink columns.
 */
async function load(url: string): Promise<Light[]> {
  const res = await fetch(url);
  const raw = new Uint8Array(await new Response(res.body!.pipeThrough(new DecompressionStream("gzip"))).arrayBuffer());
  const dv = new DataView(raw.buffer, raw.byteOffset, raw.byteLength);
  if (String.fromCharCode(...raw.subarray(0, 4)) !== "PLIT") throw new Error(`lights: ${url} is not a PLIT file`);
  const n = dv.getUint32(4, true);
  const flags = dv.getUint32(8, true);
  let o = 12;
  const f32 = () => {
    const a = new Float32Array(n);
    for (let i = 0; i < n; i++, o += 4) a[i] = dv.getFloat32(o, true);
    return a;
  };
  const u8 = () => {
    const a = raw.slice(o, o + n);
    o += n;
    return a;
  };
  const x = f32();
  const y = f32();
  const z = f32();
  const r = u8();
  const g = u8();
  const b = u8();
  const intensity = f32();
  const radius = f32();
  const phase = u8();
  const twinkle = u8();
  const path = flags & 1 ? [f32(), f32(), f32(), f32()] : null;
  const blink = flags & 2 ? [f32(), f32()] : null;
  const out: Light[] = [];
  for (let i = 0; i < n; i++)
    out.push({
      x: x[i],
      y: y[i],
      z: z[i],
      r: r[i] / 255,
      g: g[i] / 255,
      b: b[i] / 255,
      intensity: intensity[i],
      radius: radius[i],
      phase: phase[i] / 255,
      twinkle: twinkle[i] / 255,
      path: path ? [path[0][i], path[1][i], path[2][i], path[3][i]] : undefined,
      blink: blink ? [blink[0][i], blink[1][i]] : undefined,
    });
  return out;
}

const [CITY, SIGNALS, TRAFFIC] = await Promise.all([load(cityUrl), load(signalsUrl), load(trafficUrl)]);

/** The light sets: the static field, the signals, the traffic streams (the cooker grows light cells with distance). */
export function cityLightSets(): LightSet[] {
  const city = new LightSet("city");
  for (const l of CITY) city.add(l);
  const signals = new LightSet("signals");
  for (const l of SIGNALS) signals.add(l);
  const traffic = new LightSet("traffic");
  for (const l of TRAFFIC) traffic.add(l);
  return [city, signals, traffic];
}

/** Counts for the build log. */
export const CITY_COUNTS = { static: CITY.length, signals: SIGNALS.length, moving: TRAFFIC.length };
