import type { CityDef } from "../core/types";

/**
 * Every destination on the globe. `load` is the only thing that makes a city
 * enterable; its scene module is code-split so the globe starts fast.
 */
export const CITIES: CityDef[] = [
  {
    id: "tokyo",
    name: "Tokyo",
    native: "東京",
    country: "Japan",
    lat: 35.7101,
    lon: 139.8107,
    timeZone: "Asia/Tokyo",
    status: "live",
    scene: "Rainy Night Konbini",
    sceneNative: "雨夜のコンビニ",
    weather: "Rain · 14°C",
    accent: "#4fe3c1",
    load: () => import("../tokyo/index"),
  },
  {
    id: "hong-kong",
    name: "Hong Kong",
    native: "香港",
    country: "China",
    lat: 22.3193,
    lon: 114.1694,
    timeZone: "Asia/Hong_Kong",
    status: "soon",
    scene: "Dai Pai Dong under Neon",
    sceneNative: "霓虹大排檔",
    weather: "Humid · 27°C",
    accent: "#ff4f7a",
  },
  {
    id: "seoul",
    name: "Seoul",
    native: "서울",
    country: "South Korea",
    lat: 37.5665,
    lon: 126.978,
    timeZone: "Asia/Seoul",
    status: "soon",
    scene: "Pojangmacha in the Snow",
    sceneNative: "눈 오는 포장마차",
    weather: "Snow · −3°C",
    accent: "#ff8a3d",
  },
  {
    id: "shanghai",
    name: "Shanghai",
    native: "上海",
    country: "China",
    lat: 31.2304,
    lon: 121.4737,
    timeZone: "Asia/Shanghai",
    status: "soon",
    scene: "Longtang after Midnight",
    sceneNative: "午夜弄堂",
    weather: "Mist · 18°C",
    accent: "#ffcf5a",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    native: "मुंबई",
    country: "India",
    lat: 19.076,
    lon: 72.8777,
    timeZone: "Asia/Kolkata",
    status: "soon",
    scene: "Monsoon Chai Stall",
    sceneNative: "मानसून चाय",
    weather: "Monsoon · 28°C",
    accent: "#ffb347",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    native: "İstanbul",
    country: "Türkiye",
    lat: 41.0082,
    lon: 28.9784,
    timeZone: "Europe/Istanbul",
    status: "soon",
    scene: "Last Ferry at Blue Hour",
    sceneNative: "Mavi Saatte Son Vapur",
    weather: "Breeze · 16°C",
    accent: "#6ab8ff",
  },
  {
    id: "paris",
    name: "Paris",
    native: "Paris",
    country: "France",
    lat: 48.8566,
    lon: 2.3522,
    timeZone: "Europe/Paris",
    status: "soon",
    scene: "Café at Closing Time",
    sceneNative: "Le café à la fermeture",
    weather: "Drizzle · 11°C",
    accent: "#ffd28a",
  },
  {
    id: "london",
    name: "London",
    native: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lon: -0.1278,
    timeZone: "Europe/London",
    status: "soon",
    scene: "Pub in the Drizzle",
    sceneNative: "Pub in the Drizzle",
    weather: "Drizzle · 9°C",
    accent: "#e8c07a",
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    native: "Reykjavík",
    country: "Iceland",
    lat: 64.1466,
    lon: -21.9426,
    timeZone: "Atlantic/Reykjavik",
    status: "soon",
    scene: "Aurora over the Harbour",
    sceneNative: "Norðurljós við höfnina",
    weather: "Clear · −6°C",
    accent: "#7dffb2",
  },
  {
    id: "new-york",
    name: "New York",
    native: "New York",
    country: "United States",
    lat: 40.7128,
    lon: -74.006,
    timeZone: "America/New_York",
    status: "soon",
    scene: "Diner at 3 AM",
    sceneNative: "Diner at 3 AM",
    weather: "Steam · 7°C",
    accent: "#ff5f5f",
  },
  {
    id: "san-francisco",
    name: "San Francisco",
    native: "San Francisco",
    country: "United States",
    lat: 37.7749,
    lon: -122.4194,
    timeZone: "America/Los_Angeles",
    status: "soon",
    scene: "Fog over Russian Hill",
    sceneNative: "Fog over Russian Hill",
    weather: "Fog · 12°C",
    accent: "#ff9e6b",
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    native: "Ciudad de México",
    country: "Mexico",
    lat: 19.4326,
    lon: -99.1332,
    timeZone: "America/Mexico_City",
    status: "soon",
    scene: "Taquería at Midnight",
    sceneNative: "Taquería a medianoche",
    weather: "Clear · 15°C",
    accent: "#ff4fd8",
  },
  {
    id: "rio",
    name: "Rio de Janeiro",
    native: "Rio de Janeiro",
    country: "Brazil",
    lat: -22.9068,
    lon: -43.1729,
    timeZone: "America/Sao_Paulo",
    status: "soon",
    scene: "Hillside Lights",
    sceneNative: "Luzes do Morro",
    weather: "Warm · 24°C",
    accent: "#5fff9e",
  },
  {
    id: "sydney",
    name: "Sydney",
    native: "Sydney",
    country: "Australia",
    lat: -33.8688,
    lon: 151.2093,
    timeZone: "Australia/Sydney",
    status: "soon",
    scene: "Harbour Storm",
    sceneNative: "Harbour Storm",
    weather: "Storm · 19°C",
    accent: "#63d2ff",
  },
  {
    id: "cairo",
    name: "Cairo",
    native: "القاهرة",
    country: "Egypt",
    lat: 30.0444,
    lon: 31.2357,
    timeZone: "Africa/Cairo",
    status: "soon",
    scene: "Rooftop over the Nile",
    sceneNative: "سطح فوق النيل",
    weather: "Dry · 22°C",
    accent: "#ffc36b",
  },
];

export function cityById(id: string): CityDef | undefined {
  return CITIES.find((c) => c.id === id);
}

export function localTime(city: CityDef, date = new Date()): string {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: city.timeZone,
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date);
}
