// One vertex and one fragment source, compiled per program with a #define:
// surfaces (texture x cooked vertex colour, fog), CUT (alpha test), GLOW (an
// emission map added to the lit texture), WET (planar mirror through a puddle
// mask), WATER (two wave layers, sky by Fresnel) and FIELD (light sprites). The arithmetic of WET and WATER is
// n3ds/src/wet.v.pica and water.v.pica.
static const char vertex_source[] =
    "#ifdef FIELD\n"
    "attribute vec4 aPos, aUV, aColor, aAnim;\n" // xyz radius; path cycles; colour twinkle; phase blink duty 1/k
    "uniform mat4 uMVP; uniform vec3 uEye; uniform vec4 uField; uniform vec2 uClock;\n"
    "varying lowp vec3 vColor;\n"
    "void main() {\n"
    "  vec3 v = aPos.xyz + aUV.xyz * fract(aAnim.x + aUV.w * uClock.x) - uEye;\n"
    "  float d = max(length(v), 0.01);\n"
    "  float size = aPos.w * uField.x / d;\n"
    "  gl_PointSize = clamp(size, uField.y, uField.z);\n"
    "  float on = step(fract(aAnim.x + aAnim.y * uClock.x), aAnim.z);\n"
    "  float twinkle = 1.0 + aColor.a * 0.25 * sin(aAnim.x * 86.08 + uClock.y);\n"
    "  vColor = aColor.rgb * (min(size / gl_PointSize, 1.0) * aAnim.w * twinkle * on);\n"
    "  gl_Position = uMVP * vec4(uEye + v * (1.0 - clamp(uField.w * d, 0.002, 0.5)), 1.0);\n"
    "}\n"
    "#else\n"
    "attribute vec3 aPos; attribute vec2 aUV; attribute vec4 aColor;\n"
    "uniform mat4 uMVP, uMirror; uniform vec4 uUV, uTint; uniform float uFog, uMask;\n"
    "uniform vec3 uEye, uWet, uWave0, uWave1, uSky;\n"
    "varying vec2 vUV, vUV2; varying vec3 vMirror; varying lowp vec4 vColor; varying lowp float vFog;\n"
    "void main() {\n"
    "  gl_Position = uMVP * vec4(aPos, 1.0);\n"
    "  vUV = aUV * uUV.xy + uUV.zw;\n"
    "  vColor = aColor * uTint;\n"
    "  float f = uFog * gl_Position.w;\n"
    "  vFog = 1.0 - exp(-f * f);\n"
    "#if defined(WET) || defined(WATER)\n"
    "  float graze = 1.0 - abs(normalize(uEye - aPos).y);\n"
    "#endif\n"
    "#ifdef WET\n"
    "  vec4 m = uMirror * vec4(aPos, 1.0);\n"
    "  vMirror = vec3((m.xy + m.w) * 0.5, m.w);\n"
    "  vUV2 = aPos.xz * uWet.z;\n"
    "  vColor.a = uWet.x + uWet.y * graze * graze;\n"
    "#endif\n"
    "#ifdef WATER\n"
    "  vUV = aPos.xz * uWave0.x + uWave0.yz;\n"
    "  vUV2 = aPos.xz * uWave1.x + uWave1.yz;\n"
    "  float k = max(graze - uMask, 0.0);\n"
    "  vColor.rgb = mix(aColor.rgb, uSky, min(k * k * k * k * k + 0.02, 1.0)) * uTint.rgb;\n"
    "#endif\n"
    "}\n"
    "#endif\n";
static const char fragment_source[] =
    "#ifdef FIELD\n"
    "varying lowp vec3 vColor;\n"
    "void main() {\n"
    "  mediump vec2 q = gl_PointCoord * 2.0 - 1.0;\n"
    "  lowp float f = clamp(1.0 - dot(q, q), 0.0, 1.0);\n"
    "  gl_FragColor = vec4(vColor * (f * f), 1.0);\n"
    "}\n"
    "#else\n"
    "uniform sampler2D uTex, uMirrorTex, uPuddle, uGlow; uniform lowp vec3 uFogColor; uniform lowp float uCut;\n"
    "varying highp vec2 vUV, vUV2; varying highp vec3 vMirror; varying lowp vec4 vColor; varying lowp float vFog;\n"
    "void main() {\n"
    "#if defined(WATER)\n"
    "  lowp vec4 c = vec4(texture2D(uTex, vUV).rgb * texture2D(uTex, vUV2).rgb * vColor.rgb, 1.0);\n"
    "#elif defined(WET)\n"
    "  lowp float k = texture2D(uPuddle, vUV2).r * vColor.a;\n"
    "  lowp vec4 c = vec4(mix(texture2D(uTex, vUV).rgb * vColor.rgb, texture2DProj(uMirrorTex, vMirror).rgb, k), 1.0);\n"
    "#elif defined(GLOW)\n"
    "  lowp vec4 c = vec4(texture2D(uTex, vUV).rgb * vColor.rgb + texture2D(uGlow, vUV).rgb * vColor.a, 1.0);\n"
    "#else\n"
    "  lowp vec4 c = texture2D(uTex, vUV) * vColor;\n"
    "#endif\n"
    "#ifdef CUT\n"
    "  if (c.a < uCut) discard;\n"
    "#endif\n"
    "  gl_FragColor = vec4(mix(c.rgb, uFogColor, vFog), c.a);\n"
    "}\n"
    "#endif\n";
